fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
unsafe-fixes = true

[format]
docstring-code-format = true
line-ending = "native"
skip-magic-trailing-comma = true

[lint]
ignore = [
  "COM812",
  "D",
  "EM",
  "FBT",
  "INP001",
  "PLR2004",
  "PTH123",
  "RUF013",
  "T201",
  "TRY003"
]
select = ["ALL"]

[lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
combine-as-imports = true
extra-standard-library = ["framebuf", "machine", "network", "ntptime", "ucollections", "ujson", "utime"]
known-local-folder = ["freyr_screen", "sensor", "utils"]
known-third-party = ["dht", "urequests"]
split-on-trailing-comma = false

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

[lint.per-file-ignores]

[lint.pydocstyle]
convention = "google"

[lint.pyupgrade]
keep-runtime-typing = true
