fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
target-version = "py37"
unsafe-fixes = true

[format]
docstring-code-format = true
line-ending = "native"
skip-magic-trailing-comma = true

[lint]
ignore = [
  "COM812",
  "D",
  "EM",
  "FA",
  "FBT",
  "INP001",
  "PLR2004",
  "PTH123",
  "RUF013",
  "T201",
  "TRY003"
]
select = ["ALL"]

[lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
combine-as-imports = true
extra-standard-library = ["framebuf", "machine", "network", "ntptime", "ucollections", "ujson", "utime"]
known-local-folder = ["bin_lights", "clock", "screen", "sensor", "temperature_screen", "utils"]
known-third-party = ["dht", "urequests"]
split-on-trailing-comma = false

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

[lint.per-file-ignores]
"bin-lights/bin_lights.py" = ["ANN205", "BLE001", "RUF012"]
"freyr-screen/main.py" = ["ERA001"]
"temperature-screen/clock.py" = ["BLE001"]
"temperature-screen/temperature_screen.py" = ["PERF203", "SIM105"]

[lint.pydocstyle]
convention = "google"

[lint.pyupgrade]
keep-runtime-typing = true
