fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
unsafe-fixes = true

[format]
docstring-code-format = true
exclude = ["config.py"]
line-ending = "native"
skip-magic-trailing-comma = true

[lint]
exclude = ["config.py"]
ignore = [
  "COM812",
  "D",
  "EM102",
  "FA",
  "FBT",
  "INP001",
  "PERF203",
  "PLR2004",
  "PLW2901",
  "PTH",
  "RUF013",
  "SIM105",
  "T",
  "TRY003",
  "TRY300"
]
select = ["ALL"]

[lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
combine-as-imports = true
extra-standard-library = ["framebuf", "machine", "network", "ntptime", "ucollections", "ujson", "utime"]
known-local-folder = ["config", "freyr_screen", "freyr_sensor", "utils"]
known-third-party = ["dht", "urequests"]
split-on-trailing-comma = false

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

[lint.per-file-ignores]

[lint.pydocstyle]
convention = "google"

[lint.pyupgrade]
keep-runtime-typing = true
